### ISSUE TITLE
docs: Document is out of date

### ISSUE THREAD

**Issue by truongkhanhduy95** [vietai/dab#1]
back_translate.py file has been changed in some parameters. Please update the document. Thank you for this awsome lib!

**Comment by thtrieu** [comment]
Hi, we removed the flag `--lang`. Is this what you need?
https://github.com/vietai/dab/commit/80ef21b73127215928759262759ea5b641e5da97

**Comment by thtrieu** [comment]
We fixed the documentation and code such that the [collab here](https://github.com/vietai/dab/blob/master/colab/Sentiment_Analysis_%2B_Back_translation.ipynb) is running fine now.

We will close the issue for now. Thank you and feel free to reopen it if there are any remaining concerns.
